############################################################
# +------------------------------------------------------+ #
# |                     Informations                     | #
# +------------------------------------------------------+ #
############################################################

# This is the configuration file for SwiftUtils.

# This configuration file was generated for version ${project.version}.

# If you need help with the configuration of the plugin,
# you can join our discord server at: https://discord.gg/fSzK79TAYf

# For more information about how to configure SwiftUtils, check our Wiki at: https://swiftteam.gitbook.io/swiftutils

############################################################
# +------------------------------------------------------+ #
# |                    Main Settings                     | #
# +------------------------------------------------------+ #
############################################################

# Please do not change this value as it may cause the file to be reset.
# Default: 1.0
config-version: "1.0"

############################################################
# +------------------------------------------------------+ #
# |                     Permissions                      | #
# +------------------------------------------------------+ #
############################################################

# Here you can change the permissions for the different commands.
# Check default permissions here: https://swiftteam.gitbook.io/swiftutils/permissions
commands:
  swiftutils: swiftutils.command.swiftutils